### ISSUE TITLE
How to change back to default font

### ISSUE THREAD

**Issue by zhupengyu1231** [drytarius/CS2FM#1]

**Comment by swai-js** [comment]
Verifying the game files should revert it back to default font.

To verify:

Open your Game Library on Steam

Right-click on Counter-Strike 2

Select Properties from the menu

In the Properties menu, select 'Local Files' from the left-hand panel

On the Local Files page, select 'Verify integrity of game files'



I will add the ability to revert it back to default font to the app when I next update it, as I think verifying the game files is not really a very optimal way of doing this.
